name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t asliddintursunoff/learning-ci-cd .

      - name: Run tests
        run: docker run --rm asliddintursunoff/learning-ci-cd pytest